Fix reported cases count in pie chart
rizmaulana/kotlin-mvvm-covid19 pull request #53
Opened 2020-03-30 16:27 UTC by fgaim

confirmed=active+recovered+deaths

The confirmed cases include the number of deaths and recovered cases. Therefore:
1. We should plot the count of active infections instead of confirmed cases.
2. The total reported cases (inside the pie chart) is just the same as the confirmed cases, instead of confirmed+recovered+deaths.

2020-03-30 17:30 UTC, fajarnuha requested changes

2020-03-30 17:30 UTC, fajarnuha commented on app/src/main/java/id/rizmaulana/covid19/ui/adapter/viewholders/OverviewItemViewHolder.kt
> +        with(binding){
I think you dont need to move this one

2020-03-30 17:30 UTC, fajarnuha commented on app/src/main/res/values-in/strings.xml
> +    <string name="active">Active</string>
should be `Aktif` in Indonesian

2020-03-30 17:30 UTC, fajarnuha commented on app/src/main/java/id/rizmaulana/covid19/ui/adapter/viewholders/OverviewItemViewHolder.kt
> +                PieEntry(active.toFloat(), context.getString(R.string.active)),
Changing this does not change the textview, try to change it in the layout file

2020-03-30 17:35 UTC, fajarnuha requested changes

2020-03-30 17:35 UTC, fajarnuha commented on app/src/main/java/id/rizmaulana/covid19/ui/adapter/viewholders/OverviewItemViewHolder.kt
> +            startNumberChangeAnimator(confirmed, txtConfirmed)
actually you need to change it to `active`

2020-03-30 22:21 UTC, fgaim commented on app/src/main/java/id/rizmaulana/covid19/ui/adapter/viewholders/OverviewItemViewHolder.kt
> +        with(binding){
I'm using the new variables in the 'with' clause instead of 'item.xxx', hence needed to move this up. No behavioral change it just felt cleaner.

2020-03-30 22:21 UTC, fgaim commented on app/src/main/java/id/rizmaulana/covid19/ui/adapter/viewholders/OverviewItemViewHolder.kt
> +            startNumberChangeAnimator(confirmed, txtConfirmed)
Currently, the active cases are only plotted on the chart, not shown in a text view. However, it is probably a good idea to add a separate textview for the active cases, resulting in four figures: Confirmed; Active; Recovered; and Deaths. (see new commits)

2020-03-30 22:21 UTC, fgaim commented on app/src/main/res/values-in/strings.xml
> +    <string name="active">Active</string>
Thanks for this! I don't speak Indonesian. :)

2020-03-31 15:54 UTC, fajarnuha commented
this looks good to me, can any one of you @rizmaulana @pandubaraja review this too?

2020-03-31 15:55 UTC, fajarnuha approved these changes

2020-04-01 04:24 UTC, pandubaraja approved these changes
LGTM

2020-04-01 04:25 UTC, pandubaraja commented
Can I merge this @rizmaulana ?

2020-04-01 07:06 UTC, rizmaulana commented
Sure mas @pandubaraja sorry for slow response 🙏

2020-04-01 07:06 UTC, merged